### ISSUE TITLE
关于bot可以接收闪图但是无法发送的问题

### ISSUE THREAD

**Issue by plumephoenix** [Yuri-YuzuChaN/flash_image#1]
作者大大您好，flash插件现在Bot接收到图之后，可以群发出来，但是无法私发，私发只有文字没有图片，请问如何解决？
go-cqhttp 是v0.9.40-fix5版本，flash.py未做其他修改
![图片](https://user-images.githubusercontent.com/83998495/123074578-0450ba80-d44a-11eb-8e7b-a5b298210145.png)
![图片](https://user-images.githubusercontent.com/83998495/123074743-2c401e00-d44a-11eb-9ae8-7db0242fa58f.png)

**Comment by Yuri-YuzuChaN** [comment]
> 作者大大您好，flash插件现在Bot接收到图之后，可以群发出来，但是无法私发，私发只有文字没有图片，请问如何解决？
> go-cqhttp 是v0.9.40-fix5版本，flash.py未做其他修改
> ![图片](https://user-images.githubusercontent.com/83998495/123074578-0450ba80-d44a-11eb-8e7b-a5b298210145.png)
> ![图片](https://user-images.githubusercontent.com/83998495/123074743-2c401e00-d44a-11eb-9ae8-7db0242fa58f.png)

这个是tx的问题，如果重启过gocq的话私信就没法用了，这种情况的话建议改成私发群
