### ISSUE TITLE
麻烦问一下大佬

### ISSUE THREAD

**Issue by ID114514** [Yuri-YuzuChaN/flash_image#2]
防撤回跟防闪照貌似不一样吗？防闪照默认填 True 启动bot就默认启动了，但防撤回填 True 启动bot还是处于关闭状态是什么原因呢？

**Comment by Yuri-YuzuChaN** [comment]
这个插件只是防闪照，并没有防撤回

**Comment by ID114514** [comment]
> 这个插件只是防闪照，并没有防撤回

是的，但我看隔壁那个防撤回好像也是你开的来着...

**Comment by Yuri-YuzuChaN** [comment]
防撤回我已经删了，什么问题的话我就不太清楚了，如果你是加了防撤回启动了bot，然后在改的True的话，你得在./hoshino/save_config的文件夹找防撤回的插件把里面的enable_on_default=False给改成True

**Comment by ID114514** [comment]
> 防撤回我已经删了，什么问题的话我就不太清楚了，如果你是加了防撤回启动了bot，然后在改的True的话，你得在./hoshino/save_config的文件夹找防撤回的插件把里面的enable_on_default=False给改成True

我是在关闭状态下改的True，然后开启bot后依然是关闭状态。而且save_config这个配置文件我这貌似没有找到

**Comment by ID114514** [comment]
> `C:\Users\Administrator\.hoshino\service_config` 这个路径下面没有吗

还想麻烦问下大佬，用户组权限如何更改？例如想禁用此功能，会提示需要最高权限，我想把他改成群管理或者群主

**Comment by Yuri-YuzuChaN** [comment]
配置文件改`manage_priv`，管理员 21，群主 22

**Comment by ID114514** [comment]
> 配置文件改`manage_priv`，管理员 21，群主 22

ok。多谢大佬了
