### ISSUE TITLE
机器人接收群闪照时提示list index out of range

### ISSUE THREAD

**Issue by Ble55me** [Yuri-YuzuChaN/flash_image#3]
大佬机器人装了插件后收到闪照弹这个报错是什么原因呀，该怎么解决呢
![-349729dfaf54a036](https://user-images.githubusercontent.com/98486039/194742794-83431bec-b1f0-4a7d-9bac-37a6080fbcd0.png)

**Comment by Yuri-YuzuChaN** [comment]
这个不是我的闪照插件，你这个是nonebot2的插件，你找错人了
